import React from 'react';
import {FaCircle,FaStar} from 'react-icons/fa';
import {FiChevronRight, FiShoppingBag, FiCheckSquare} from 'react-icons/fi';

export const header = [
    {
        logo:'Bazar.com',
    }
]

export const sliderMune = [
    {
        id: 1,
        name:'this image',
        image:'../img/slider1.jpg',
    },
    {
        id: 2,
        name:'this image',
        image:'../img/slider2.jpg',
    },
    {
        id: 3,
        name:'this image',
        image:'../img/slider3.jpg',
    },
    {
        id: 4,
        name:'this image',
        image:'../img/slider4.jpg',
    },
    {
        id: 5,
        name:'this image',
        image:'../img/slider5.jpg',
    },
]

export const sliderLeft = [
    {
        page:'MY BAZAR',
        links: [
            {
                circle : <FaCircle/>,
                product : 'Shirt',
                icon: <FiChevronRight/>,
            },
            {
                circle : <FaCircle/>,
                product : 'T-Shart',
                icon: <FiChevronRight/>,
            },
            {
                circle : <FaCircle/>,
                product : 'Three Piece',
                icon: <FiChevronRight/>,
            },
            {
                circle : <FaCircle/>,
                product : 'Ladies Leather',
                icon: <FiChevronRight/>,
            },
            {
                circle : <FaCircle/>,
                product : 'Lader Many Bag',
                icon: <FiChevronRight/>,
            },
            {
                circle : <FaCircle/>,
                product : 'School Bag',
                icon: <FiChevronRight/>,
            },
            {
                circle : <FaCircle/>,
                product : 'Saree New Collection',
                icon: <FiChevronRight/>,
            },
            {
                circle : <FaCircle/>,
                product : 'Electronics Device',
                icon: <FiChevronRight/>,
            },
            {
                circle : <FaCircle/>,
                product : 'Jeans Pants',
                icon: <FiChevronRight/>,
            },
            {
                circle : <FaCircle/>,
                product : 'Ladies Pants',
                icon: <FiChevronRight/>,
            },
        ]
    },
]
export const sliderRight = [
    {
        page :'Diwali Preparation Sale',
        links: [
            {
                title: 'Free shipping',
                info: 'Source now',
                image: '../img/offer1.jpg',
            },
            {
                title: 'Free shipping',
                info: 'Source now',
                image: '../img/offer2.jpg',
            },
            {
                title: 'Free shipping',
                info: 'Source now',
                image: 'img/offer3.jpg',
            },
        ]
    },
]
export const productsOne = [
    {
        id:1,
        image:'https://s.alicdn.com/@sc04/kf/He610cf6a8c35425a914b51b471e97c97t.jpg',
        title:'Mayur Saree Poly Silk Pink Color New Glitter work Heavy wedding Saree',
        bag:<FiShoppingBag/>,
        bagtext:'Buy Now',
        // cart list End here 
        code:'SKU:0X50874',
        brand:'BRAND',
        number:'No.1',
        more:'More Security Safe from No.1',
        price:2000,
        priceinfo:'Starting price',
        checktext:'Check Avaliable Shop',
        Warranty:'Warranty',
        icon:<FiCheckSquare/>,
        Authentic:'100% Authentic',
        // review End here 

        infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
        infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
        info1:'Saree',
        info2:'Cotton Jamdani',
        info3:'12.5 Hand',
        info4:'Bangladesh',
        info5:'Gender',
        // details End here
        outsidetext:'Available Shops',
        carttitle:'Cash on Delivery Service',
        stock:'Stock available',
        rating:5,
        ratingicon: <FaStar/>,
        amount:1,
    },
    {
        id: 2,
        image: 'https://s.alicdn.com/@sc04/kf/U93fe8a52e2f0419890a194ec48d262fc6.jpg_220x220.jpg_.webp',
        title:'2020 beautiful red color plane kurti fore women',
        bag:<FiShoppingBag/>,
        bagtext:'Buy Now',
        // cart list End here 
        code:'SKU:0X50874',
        brand:'BRAND',
        number:'No.1',
        more:'More Security Safe from No.1',
        price:1700,
        priceinfo:'Starting price',
        checktext:'Check Avaliable Shop',
        Warranty:'Warranty',
        icon:<FiCheckSquare/>,
        Authentic:'100% Authentic',
        // review End here 

        infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
        infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
        info1:'Saree',
        info2:'Cotton Jamdani',
        info3:'12.5 Hand',
        info4:'Bangladesh',
        info5:'Gender',
        // details End here
        outsidetext:'Available Shops',
        carttitle:'Cash on Delivery Service',
        stock:'Stock available',
        rating:5,
        ratingicon: <FaStar/>,
        amount:1,
        
    },
    {
        id: 3,
        image: 'https://s.alicdn.com/@sc04/kf/U3f20d5fed42444ffbf43b00d5ffd2e4e9.jpg_220x220.jpg_.webp',
        title:'100% cotton purple color simple kurta for ladies',
        bag:<FiShoppingBag/>,
        bagtext:'Buy Now',
        // cart list End here 
        code:'SKU:0X50874',
        brand:'BRAND',
        number:'No.1',
        more:'More Security Safe from No.1',
        price: 1200,
        priceinfo:'Starting price',
        checktext:'Check Avaliable Shop',
        Warranty:'Warranty',
        icon:<FiCheckSquare/>,
        Authentic:'100% Authentic',
        // review End here 

        infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
        infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
        info1:'Saree',
        info2:'Cotton Jamdani',
        info3:'12.5 Hand',
        info4:'Bangladesh',
        info5:'Gender',
        // details End here
        outsidetext:'Available Shops',
        carttitle:'Cash on Delivery Service',
        stock:'Stock available',
        rating:5,
        ratingicon: <FaStar/>,
        amount:1,
    },
    {
        id: 4,
        image: 'https://s.alicdn.com/@sc04/kf/Ua7ea7b4eb0f04ed4b5d1f02492a06c16q.jpg_220x220.jpg_.webp',
        title:'2020 light green plane kurti for women - single color plane kurti for ladies',
        bag:<FiShoppingBag/>,
        bagtext:'Buy Now',
        // cart list End here 
        code:'SKU:0X50874',
        brand:'BRAND',
        number:'No.1',
        more:'More Security Safe from No.1',
        price: 1800,
        priceinfo:'Starting price',
        checktext:'Check Avaliable Shop',
        Warranty:'Warranty',
        icon:<FiCheckSquare/>,
        Authentic:'100% Authentic',
        // review End here 

        infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
        infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
        info1:'Saree',
        info2:'Cotton Jamdani',
        info3:'12.5 Hand',
        info4:'Bangladesh',
        info5:'Gender',
        // details End here
        outsidetext:'Available Shops',
        carttitle:'Cash on Delivery Service',
        stock:'Stock available',
        rating:5,
        ratingicon: <FaStar/>,
        amount:1,
    },
    {
        id: 5,
        image: 'https://s.alicdn.com/@sc04/kf/UTB8ZwMBFlahduJk43Jaq6zM8FXaF.jpg_300x300.jpg',
        title:'Wedding Saree / Saree Blouse Patterns / Cotton Silk Saree',
        bag:<FiShoppingBag/>,
        bagtext:'Buy Now',
        // cart list End here 
        code:'SKU:0X50874',
        brand:'BRAND',
        number:'No.1',
        more:'More Security Safe from No.1',
        price: 1300,
        priceinfo:'Starting price',
        checktext:'Check Avaliable Shop',
        Warranty:'Warranty',
        icon:<FiCheckSquare/>,
        Authentic:'100% Authentic',
        // review End here 

        infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
        infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
        info1:'Saree',
        info2:'Cotton Jamdani',
        info3:'12.5 Hand',
        info4:'Bangladesh',
        info5:'Gender',
        // details End here
        outsidetext:'Available Shops',
        carttitle:'Cash on Delivery Service',
        stock:'Stock available',
        rating:5,
        ratingicon: <FaStar/>,
        amount:1,
    },
    {
        id: 6,
        image: 'https://s.alicdn.com/@sc04/kf/Uc2b27e65ef0f4d449c5b60cad2a97ff9Z.jpg_300x300.jpg',
        title:'Party wear designer embroidered net silk flower design Indian ladies wear orange color saree with blouse piece pearl work sari',
        bag:<FiShoppingBag/>,
        bagtext:'Buy Now',
        // cart list End here 
        code:'SKU:0X50874',
        brand:'BRAND',
        number:'No.1',
        more:'More Security Safe from No.1',
        price: 1250,
        priceinfo:'Starting price',
        checktext:'Check Avaliable Shop',
        Warranty:'Warranty',
        icon:<FiCheckSquare/>,
        Authentic:'100% Authentic',
        // review End here 
        infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
        infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
        info1:'Saree',
        info2:'Cotton Jamdani',
        info3:'12.5 Hand',
        info4:'Bangladesh',
        info5:'Gender',
        // details End here
        outsidetext:'Available Shops',
        carttitle:'Cash on Delivery Service',
        stock:'Stock available',
        rating:5,
        ratingicon: <FaStar/>,
        amount:1,
    },
    {
        id: 7,
        image: 'https://s.alicdn.com/@sc04/kf/UTB81C2Alf2JXKJkSanrq6y3lVXac.jpg_300x300.jpg',
        title:'R & D Exports Banglory Silk Fancy Wedding / Party Wear Indian Saree',
        bag:<FiShoppingBag/>,
        bagtext:'Buy Now',
        // cart list End here 
        code:'SKU:0X50874',
        brand:'BRAND',
        number:'No.1',
        more:'More Security Safe from No.1',
        price: 3200,
        priceinfo:'Starting price',
        checktext:'Check Avaliable Shop',
        Warranty:'Warranty',
        icon:<FiCheckSquare/>,
        Authentic:'100% Authentic',
        // review End here 

        infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
        infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
        info1:'Saree',
        info2:'Cotton Jamdani',
        info3:'12.5 Hand',
        info4:'Bangladesh',
        info5:'Gender',
        // details End here
        outsidetext:'Available Shops',
        carttitle:'Cash on Delivery Service',
        stock:'Stock available',
        rating:5,
        ratingicon: <FaStar/>,
        amount:1,
    },
    {
        id: 8,
        image: 'https://s.alicdn.com/@sc04/kf/U231e91c10dad4772993fccfd7ac557cfU.jpg_300x300.jpg',
        title:'Dcb Fashion Exports Indian Embroidery Wedding & Party Wear Silk Maroon Saree with Heavy Work Bridal Sarees Low Price',
        bag:<FiShoppingBag/>,
        bagtext:'Buy Now',
        // cart list End here 
        code:'SKU:0X50874',
        brand:'BRAND',
        number:'No.1',
        more:'More Security Safe from No.1',
        price: 4500,
        priceinfo:'Starting price',
        checktext:'Check Avaliable Shop',
        Warranty:'Warranty',
        icon:<FiCheckSquare/>,
        Authentic:'100% Authentic',
        // review End here 

        infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
        infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
        info1:'Saree',
        info2:'Cotton Jamdani',
        info3:'12.5 Hand',
        info4:'Bangladesh',
        info5:'Gender',
        // details End here
        outsidetext:'Available Shops',
        carttitle:'Cash on Delivery Service',
        stock:'Stock available',
        rating:5,
        ratingicon: <FaStar/>,
        amount:1,
    },
    {
        id: 9,
        image: 'https://s.alicdn.com/@sc04/kf/UTB8ZwMBFlahduJk43Jaq6zM8FXaF.jpg_300x300.jpg',
        title:'Wedding Saree / Saree Blouse Patterns / Cotton Silk Saree',
        bag:<FiShoppingBag/>,
        bagtext:'Buy Now',
        // cart list End here 
        code:'SKU:0X50874',
        brand:'BRAND',
        number:'No.1',
        more:'More Security Safe from No.1',
        price: 1300,
        priceinfo:'Starting price',
        checktext:'Check Avaliable Shop',
        Warranty:'Warranty',
        icon:<FiCheckSquare/>,
        Authentic:'100% Authentic',
        // review End here 

        infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
        infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
        info1:'Saree',
        info2:'Cotton Jamdani',
        info3:'12.5 Hand',
        info4:'Bangladesh',
        info5:'Gender',
        // details End here
        outsidetext:'Available Shops',
        carttitle:'Cash on Delivery Service',
        stock:'Stock available',
        rating:5,
        ratingicon: <FaStar/>,
        amount:1,
    },
    {
        id: 10,
        image: 'https://s.alicdn.com/@sc04/kf/Uc2b27e65ef0f4d449c5b60cad2a97ff9Z.jpg_300x300.jpg',
        title:'Party wear designer embroidered net silk flower design Indian ladies wear orange color saree with blouse piece pearl work sari',
        bag:<FiShoppingBag/>,
        bagtext:'Buy Now',
        // cart list End here 
        code:'SKU:0X50874',
        brand:'BRAND',
        number:'No.1',
        more:'More Security Safe from No.1',
        price: 1250,
        priceinfo:'Starting price',
        checktext:'Check Avaliable Shop',
        Warranty:'Warranty',
        icon:<FiCheckSquare/>,
        Authentic:'100% Authentic',
        // review End here 
        infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
        infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
        info1:'Saree',
        info2:'Cotton Jamdani',
        info3:'12.5 Hand',
        info4:'Bangladesh',
        info5:'Gender',
        // details End here
        outsidetext:'Available Shops',
        carttitle:'Cash on Delivery Service',
        stock:'Stock available',
        rating:5,
        ratingicon: <FaStar/>,
        amount:1,
    },
    {
        id: 11,
        image: 'https://s.alicdn.com/@sc04/kf/UTB81C2Alf2JXKJkSanrq6y3lVXac.jpg_300x300.jpg',
        title:'R & D Exports Banglory Silk Fancy Wedding / Party Wear Indian Saree',
        bag:<FiShoppingBag/>,
        bagtext:'Buy Now',
        // cart list End here 
        code:'SKU:0X50874',
        brand:'BRAND',
        number:'No.1',
        more:'More Security Safe from No.1',
        price: 3200,
        priceinfo:'Starting price',
        checktext:'Check Avaliable Shop',
        Warranty:'Warranty',
        icon:<FiCheckSquare/>,
        Authentic:'100% Authentic',
        // review End here 

        infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
        infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
        info1:'Saree',
        info2:'Cotton Jamdani',
        info3:'12.5 Hand',
        info4:'Bangladesh',
        info5:'Gender',
        // details End here
        outsidetext:'Available Shops',
        carttitle:'Cash on Delivery Service',
        stock:'Stock available',
        rating:5,
        ratingicon: <FaStar/>,
        amount:1,
    },
    {
        id: 12,
        image: 'https://s.alicdn.com/@sc04/kf/U231e91c10dad4772993fccfd7ac557cfU.jpg_300x300.jpg',
        title:'Dcb Fashion Exports Indian Embroidery Wedding & Party Wear Silk Maroon Saree with Heavy Work Bridal Sarees Low Price',
        bag:<FiShoppingBag/>,
        bagtext:'Buy Now',
        // cart list End here 
        code:'SKU:0X50874',
        brand:'BRAND',
        number:'No.1',
        more:'More Security Safe from No.1',
        price: 4500,
        priceinfo:'Starting price',
        checktext:'Check Avaliable Shop',
        Warranty:'Warranty',
        icon:<FiCheckSquare/>,
        Authentic:'100% Authentic',
        // review End here 

        infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
        infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
        info1:'Saree',
        info2:'Cotton Jamdani',
        info3:'12.5 Hand',
        info4:'Bangladesh',
        info5:'Gender',
        // details End here
        outsidetext:'Available Shops',
        carttitle:'Cash on Delivery Service',
        stock:'Stock available',
        rating:5,
        ratingicon: <FaStar/>,
        amount:1,
    },

]
export const productsTwo = [
    {
        outoftitle:'Home Appliance',
        carttwo:[
            {
                id:1,
                image:'https://s.alicdn.com/@sc04/kf/HTB18EucaMnD8KJjy1Xdq6yZsVXaX.jpg_300x300.jpg',
                title:'home appliance 1.8L Stainless steel electric kettle with paint body',
                bag:<FiShoppingBag/>,
                bagtext:'Buy Now',
                price:400,
                rating: 5,
                // ===============
                code:'SKU:0X50874',
                brand:'BRAND',
                number:'No.1',
                more:'More Security Safe from No.1',
                priceinfo:'Starting price',
                checktext:'Check Avaliable Shop',
                Warranty:'Warranty',
                icon:<FiCheckSquare/>,
                Authentic:'100% Authentic',
                 // ===============
                infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
                infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
                info1:'Saree',
                info2:'Cotton Jamdani',
                info3:'12.5 Hand',
                info4:'Bangladesh',
                info5:'Gender',
                // ===============
                outsidetext:'Available Shops',
                carttitle:'Cash on Delivery Service',
                stock:'Stock available',
                ratingicon: <FaStar/>,
                amount:1,
            },
            {
                id:102,
                image:'https://s.alicdn.com/@sc04/kf/H651f4b64fe894c539f1e8a577f6609f3f.jpg_300x300.jpg',
                title:'home appliances industrial portable negative ion hepa air purifier replacement filter',
                bag:<FiShoppingBag/>,
                bagtext:'Buy Now',
                price:10500,
                rating:5,
                // ===============
                code:'SKU:0X50874',
                brand:'BRAND',
                number:'No.1',
                more:'More Security Safe from No.1',
                priceinfo:'Starting price',
                checktext:'Check Avaliable Shop',
                Warranty:'Warranty',
                icon:<FiCheckSquare/>,
                Authentic:'100% Authentic',
                 // ===============
                infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
                infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
                info1:'Saree',
                info2:'Cotton Jamdani',
                info3:'12.5 Hand',
                info4:'Bangladesh',
                info5:'Gender',
                // ===============
                outsidetext:'Available Shops',
                carttitle:'Cash on Delivery Service',
                stock:'Stock available',
                ratingicon: <FaStar/>,
                amount:1,
            },
            {
                id:103,
                image:'https://s.alicdn.com/@sc04/kf/Uc4febecaa47d423fa7e0eac4b7f242f17.jpg_300x300.jpg',
                title:'New Design Hot Sale Electric Pressure Cookers Home Kitchen Appliance Electric Pressure Cooker',
                bag:<FiShoppingBag/>,
                bagtext:'Buy Now',
                price:2700,
                rating:5,
                // ===============
                code:'SKU:0X50874',
                brand:'BRAND',
                number:'No.1',
                more:'More Security Safe from No.1',
                priceinfo:'Starting price',
                checktext:'Check Avaliable Shop',
                Warranty:'Warranty',
                icon:<FiCheckSquare/>,
                Authentic:'100% Authentic',
                 // ===============
                infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
                infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
                info1:'Saree',
                info2:'Cotton Jamdani',
                info3:'12.5 Hand',
                info4:'Bangladesh',
                info5:'Gender',
                // ===============
                outsidetext:'Available Shops',
                carttitle:'Cash on Delivery Service',
                stock:'Stock available',
                ratingicon: <FaStar/>,
                amount:1,
            },
            {
                id:104,
                image:'https://s.alicdn.com/@sc04/kf/Hdd61009466024380ace06c14119f5a40t.jpg_300x300.jpg',
                title:'Black 8-inch Home Appliance Spare Parts Burner Parts Electric Stove Stove Drip Pans',
                bag:<FiShoppingBag/>,
                bagtext:'Buy Now',
                price:120,
                rating:5,
                // ===============
                code:'SKU:0X50874',
                brand:'BRAND',
                number:'No.1',
                more:'More Security Safe from No.1',
                priceinfo:'Starting price',
                checktext:'Check Avaliable Shop',
                Warranty:'Warranty',
                icon:<FiCheckSquare/>,
                Authentic:'100% Authentic',
                 // ===============
                infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
                infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
                info1:'Saree',
                info2:'Cotton Jamdani',
                info3:'12.5 Hand',
                info4:'Bangladesh',
                info5:'Gender',
                // ===============
                outsidetext:'Available Shops',
                carttitle:'Cash on Delivery Service',
                stock:'Stock available',
                ratingicon: <FaStar/>,
                amount:1,
            },
            {
                id:105,
                image:'https://s.alicdn.com/@sc04/kf/HTB1djvKJbvpK1RjSZPi762mwXXaq.png_300x300.png',
                title:'Portable PTC Mini Easy Home Appliance 110v 220v Electric Fan Heater',
                bag:<FiShoppingBag/>,
                bagtext:'Buy Now',
                price:1800,
                rating:5,
                // ===============
                code:'SKU:0X50874',
                brand:'BRAND',
                number:'No.1',
                more:'More Security Safe from No.1',
                priceinfo:'Starting price',
                checktext:'Check Avaliable Shop',
                Warranty:'Warranty',
                icon:<FiCheckSquare/>,
                Authentic:'100% Authentic',
                 // ===============
                infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
                infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
                info1:'Saree',
                info2:'Cotton Jamdani',
                info3:'12.5 Hand',
                info4:'Bangladesh',
                info5:'Gender',
                // ===============
                outsidetext:'Available Shops',
                carttitle:'Cash on Delivery Service',
                stock:'Stock available',
                ratingicon: <FaStar/>,
                amount:1,
            },
            {
                id:106,
                image:'https://s.alicdn.com/@sc04/kf/Hf9821965d83d4a60b6a0603e1d690dd2r.jpg_300x300.jpg',
                title:'Portable vacuum cleaner wireless car Hand Held Electric Vacuum Cleaner Home Appliance filter',
                bag:<FiShoppingBag/>,
                bagtext:'Buy Now',
                price:4040,
                rating:5,
                // ===============
                code:'SKU:0X50874',
                brand:'BRAND',
                number:'No.1',
                more:'More Security Safe from No.1',
                priceinfo:'Starting price',
                checktext:'Check Avaliable Shop',
                Warranty:'Warranty',
                icon:<FiCheckSquare/>,
                Authentic:'100% Authentic',
                 // ===============
                infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
                infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
                info1:'Saree',
                info2:'Cotton Jamdani',
                info3:'12.5 Hand',
                info4:'Bangladesh',
                info5:'Gender',
                // ===============
                outsidetext:'Available Shops',
                carttitle:'Cash on Delivery Service',
                stock:'Stock available',
                ratingicon: <FaStar/>,
                amount:1,
            },
            {
                id:107,
                image:'https://s.alicdn.com/@sc04/kf/H26fae161e6e24a72a426abdf1f92bba9c.jpg_300x300.jpg',
                title:'New Design Real Copper Beads And Amethyst Crystals Wooden Planchette Decoration Wood Home Decor',
                bag:<FiShoppingBag/>,
                bagtext:'Buy Now',
                price:800,
                rating:5,
                // ===============
                code:'SKU:0X50874',
                brand:'BRAND',
                number:'No.1',
                more:'More Security Safe from No.1',
                priceinfo:'Starting price',
                checktext:'Check Avaliable Shop',
                Warranty:'Warranty',
                icon:<FiCheckSquare/>,
                Authentic:'100% Authentic',
                 // ===============
                infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
                infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
                info1:'Saree',
                info2:'Cotton Jamdani',
                info3:'12.5 Hand',
                info4:'Bangladesh',
                info5:'Gender',
                // ===============
                outsidetext:'Available Shops',
                carttitle:'Cash on Delivery Service',
                stock:'Stock available',
                ratingicon: <FaStar/>,
                amount:1,
                
            },
            {
                id:108,
                image:'https://s.alicdn.com/@sc04/kf/UTB8osj5GtoSdeJk43Owq6ya4XXa9.jpg_300x300.jpg',
                title:'Electric Charge Home Appliance Private Custom Engraving Logo Led Indicator Nose Hair Trimmer',
                bag:<FiShoppingBag/>,
                bagtext:'Buy Now',
                price:450,
                rating:5,
                // ===============
                code:'SKU:0X50874',
                brand:'BRAND',
                number:'No.1',
                more:'More Security Safe from No.1',
                priceinfo:'Starting price',
                checktext:'Check Avaliable Shop',
                Warranty:'Warranty',
                icon:<FiCheckSquare/>,
                Authentic:'100% Authentic',
                 // ===============
                infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
                infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
                info1:'Saree',
                info2:'Cotton Jamdani',
                info3:'12.5 Hand',
                info4:'Bangladesh',
                info5:'Gender',
                // ===============
                outsidetext:'Available Shops',
                carttitle:'Cash on Delivery Service',
                stock:'Stock available',
                ratingicon: <FaStar/>,
                amount:1,
            },
            {
                id:109,
                image:'https://s.alicdn.com/@sc04/kf/H65c25e7ae90344368878dc064a03c8e1S.jpg_300x300.jpg',
                title:'MO-4501 Ambel Hot Sales Microwave Oven Home use cooking appliances Electric Microwave Oven',
                bag:<FiShoppingBag/>,
                bagtext:'Buy Now',
                price:3200,
                rating:5,
                // ===============
                code:'SKU:0X50874',
                brand:'BRAND',
                number:'No.1',
                more:'More Security Safe from No.1',
                priceinfo:'Starting price',
                checktext:'Check Avaliable Shop',
                Warranty:'Warranty',
                icon:<FiCheckSquare/>,
                Authentic:'100% Authentic',
                 // ===============
                infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
                infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
                info1:'Saree',
                info2:'Cotton Jamdani',
                info3:'12.5 Hand',
                info4:'Bangladesh',
                info5:'Gender',
                // ===============
                outsidetext:'Available Shops',
                carttitle:'Cash on Delivery Service',
                stock:'Stock available',
                ratingicon: <FaStar/>,
                amount:1,
            },
            {
                id:110,
                image:'https://s.alicdn.com/@sc04/kf/Hedb44db4125e49ef9260b750345a00a0F.jpg_300x300.jpg',
                title:'2021 Hot sale CCC Certification 360 degree rotated cordless home appliances portable water electric kettle',
                bag:<FiShoppingBag/>,
                bagtext:'Buy Now',
                price:1150,
                rating:5,
                // ===============
                code:'SKU:0X50874',
                brand:'BRAND',
                number:'No.1',
                more:'More Security Safe from No.1',
                priceinfo:'Starting price',
                checktext:'Check Avaliable Shop',
                Warranty:'Warranty',
                icon:<FiCheckSquare/>,
                Authentic:'100% Authentic',
                 // ===============
                infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
                infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
                info1:'Saree',
                info2:'Cotton Jamdani',
                info3:'12.5 Hand',
                info4:'Bangladesh',
                info5:'Gender',
                // ===============
                outsidetext:'Available Shops',
                carttitle:'Cash on Delivery Service',
                stock:'Stock available',
                ratingicon: <FaStar/>,
                amount:1,
            },
            {
                id:111,
                image:'https://s.alicdn.com/@sc04/kf/HTB1yfc1bBWD3KVjSZFsq6AqkpXal.jpg_300x300.jpg',
                title:'1500w Home Kitchen Appliances Stainless Steel Electric Tea Kettle Electric with 2.0L 220V',
                bag:<FiShoppingBag/>,
                bagtext:'Buy Now',
                price:450,
                rating:5,
                // ===============
                code:'SKU:0X50874',
                brand:'BRAND',
                number:'No.1',
                more:'More Security Safe from No.1',
                priceinfo:'Starting price',
                checktext:'Check Avaliable Shop',
                Warranty:'Warranty',
                icon:<FiCheckSquare/>,
                Authentic:'100% Authentic',
                 // ===============
                infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
                infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
                info1:'Saree',
                info2:'Cotton Jamdani',
                info3:'12.5 Hand',
                info4:'Bangladesh',
                info5:'Gender',
                // ===============
                outsidetext:'Available Shops',
                carttitle:'Cash on Delivery Service',
                stock:'Stock available',
                ratingicon: <FaStar/>,
                amount:1,
            },
            {
                id:112,
                image:'https://s.alicdn.com/@sc04/kf/Hab92b3195f9c4c6ca56699d8fc9433ecc.jpg_300x300.jpg',
                title:'USB wholesale home appliance 300ml portable blender PC bottle high speed mixer',
                bag:<FiShoppingBag/>,
                bagtext:'Buy Now',
                price:750,
                rating:5,
                // ===============
                code:'SKU:0X50874',
                brand:'BRAND',
                number:'No.1',
                more:'More Security Safe from No.1',
                priceinfo:'Starting price',
                checktext:'Check Avaliable Shop',
                Warranty:'Warranty',
                icon:<FiCheckSquare/>,
                Authentic:'100% Authentic',
                 // ===============
                infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
                infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
                info1:'Saree',
                info2:'Cotton Jamdani',
                info3:'12.5 Hand',
                iinfo4:'Bangladesh',
                info5:'Gender',
                // ===============
                outsidetext:'Available Shops',
                carttitle:'Cash on Delivery Service',
                stock:'Stock available',
                ratingicon: <FaStar/>,
                amount:1,
            },
        ]
    },
    {
        outoftitle:'Home Appliance',
        carttwo:[
            {
                id:113,
                image:'https://s.alicdn.com/@sc04/kf/HTB18EucaMnD8KJjy1Xdq6yZsVXaX.jpg_300x300.jpg',
                title:'home appliance 1.8L Stainless steel electric kettle with paint body',
                bag:<FiShoppingBag/>,
                bagtext:'Buy Now',
                price:400,
                rating: 5,
                // ===============
                code:'SKU:0X50874',
                brand:'BRAND',
                number:'No.1',
                more:'More Security Safe from No.1',
                priceinfo:'Starting price',
                checktext:'Check Avaliable Shop',
                Warranty:'Warranty',
                icon:<FiCheckSquare/>,
                Authentic:'100% Authentic',
                 // ===============
                infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
                infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
                info1:'Saree',
                info2:'Cotton Jamdani',
                info3:'12.5 Hand',
                info4:'Bangladesh',
                info5:'Gender',
                // ===============
                outsidetext:'Available Shops',
                carttitle:'Cash on Delivery Service',
                stock:'Stock available',
                ratingicon: <FaStar/>,
                amount:1,
            },
            {
                id:114,
                image:'https://s.alicdn.com/@sc04/kf/H651f4b64fe894c539f1e8a577f6609f3f.jpg_300x300.jpg',
                title:'home appliances industrial portable negative ion hepa air purifier replacement filter',
                bag:<FiShoppingBag/>,
                bagtext:'Buy Now',
                price:10500,
                rating:5,
                // ===============
                code:'SKU:0X50874',
                brand:'BRAND',
                number:'No.1',
                more:'More Security Safe from No.1',
                priceinfo:'Starting price',
                checktext:'Check Avaliable Shop',
                Warranty:'Warranty',
                icon:<FiCheckSquare/>,
                Authentic:'100% Authentic',
                 // ===============
                infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
                infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
                info1:'Saree',
                info2:'Cotton Jamdani',
                info3:'12.5 Hand',
                info4:'Bangladesh',
                info5:'Gender',
                // ===============
                outsidetext:'Available Shops',
                carttitle:'Cash on Delivery Service',
                stock:'Stock available',
                ratingicon: <FaStar/>,
                amount:1,
            },
            {
                id:115,
                image:'https://s.alicdn.com/@sc04/kf/Uc4febecaa47d423fa7e0eac4b7f242f17.jpg_300x300.jpg',
                title:'New Design Hot Sale Electric Pressure Cookers Home Kitchen Appliance Electric Pressure Cooker',
                bag:<FiShoppingBag/>,
                bagtext:'Buy Now',
                price:2700,
                rating:5,
                // ===============
                code:'SKU:0X50874',
                brand:'BRAND',
                number:'No.1',
                more:'More Security Safe from No.1',
                priceinfo:'Starting price',
                checktext:'Check Avaliable Shop',
                Warranty:'Warranty',
                icon:<FiCheckSquare/>,
                Authentic:'100% Authentic',
                 // ===============
                infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
                infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
                info1:'Saree',
                info2:'Cotton Jamdani',
                info3:'12.5 Hand',
                info4:'Bangladesh',
                info5:'Gender',
                // ===============
                outsidetext:'Available Shops',
                carttitle:'Cash on Delivery Service',
                stock:'Stock available',
                ratingicon: <FaStar/>,
                amount:1,
            },
            {
                id:116,
                image:'https://s.alicdn.com/@sc04/kf/Hdd61009466024380ace06c14119f5a40t.jpg_300x300.jpg',
                title:'Black 8-inch Home Appliance Spare Parts Burner Parts Electric Stove Stove Drip Pans',
                bag:<FiShoppingBag/>,
                bagtext:'Buy Now',
                price:120,
                rating:5,
                // ===============
                code:'SKU:0X50874',
                brand:'BRAND',
                number:'No.1',
                more:'More Security Safe from No.1',
                priceinfo:'Starting price',
                checktext:'Check Avaliable Shop',
                Warranty:'Warranty',
                icon:<FiCheckSquare/>,
                Authentic:'100% Authentic',
                 // ===============
                infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
                infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
                info1:'Saree',
                info2:'Cotton Jamdani',
                info3:'12.5 Hand',
                info4:'Bangladesh',
                info5:'Gender',
                // ===============
                outsidetext:'Available Shops',
                carttitle:'Cash on Delivery Service',
                stock:'Stock available',
                ratingicon: <FaStar/>,
                amount:1,
            },
            {
                id:117,
                image:'https://s.alicdn.com/@sc04/kf/HTB1djvKJbvpK1RjSZPi762mwXXaq.png_300x300.png',
                title:'Portable PTC Mini Easy Home Appliance 110v 220v Electric Fan Heater',
                bag:<FiShoppingBag/>,
                bagtext:'Buy Now',
                price:1800,
                rating:5,
                // ===============
                code:'SKU:0X50874',
                brand:'BRAND',
                number:'No.1',
                more:'More Security Safe from No.1',
                priceinfo:'Starting price',
                checktext:'Check Avaliable Shop',
                Warranty:'Warranty',
                icon:<FiCheckSquare/>,
                Authentic:'100% Authentic',
                 // ===============
                infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
                infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
                info1:'Saree',
                info2:'Cotton Jamdani',
                info3:'12.5 Hand',
                info4:'Bangladesh',
                info5:'Gender',
                // ===============
                outsidetext:'Available Shops',
                carttitle:'Cash on Delivery Service',
                stock:'Stock available',
                ratingicon: <FaStar/>,
                amount:1,
            },
            {
                id:118,
                image:'https://s.alicdn.com/@sc04/kf/Hf9821965d83d4a60b6a0603e1d690dd2r.jpg_300x300.jpg',
                title:'Portable vacuum cleaner wireless car Hand Held Electric Vacuum Cleaner Home Appliance filter',
                bag:<FiShoppingBag/>,
                bagtext:'Buy Now',
                price:4040,
                rating:5,
                // ===============
                code:'SKU:0X50874',
                brand:'BRAND',
                number:'No.1',
                more:'More Security Safe from No.1',
                priceinfo:'Starting price',
                checktext:'Check Avaliable Shop',
                Warranty:'Warranty',
                icon:<FiCheckSquare/>,
                Authentic:'100% Authentic',
                 // ===============
                infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
                infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
                info1:'Saree',
                info2:'Cotton Jamdani',
                info3:'12.5 Hand',
                info4:'Bangladesh',
                info5:'Gender',
                // ===============
                outsidetext:'Available Shops',
                carttitle:'Cash on Delivery Service',
                stock:'Stock available',
                ratingicon: <FaStar/>,
                amount:1,
            },
            {
                id:119,
                image:'https://s.alicdn.com/@sc04/kf/H26fae161e6e24a72a426abdf1f92bba9c.jpg_300x300.jpg',
                title:'New Design Real Copper Beads And Amethyst Crystals Wooden Planchette Decoration Wood Home Decor',
                bag:<FiShoppingBag/>,
                bagtext:'Buy Now',
                price:800,
                rating:5,
                // ===============
                code:'SKU:0X50874',
                brand:'BRAND',
                number:'No.1',
                more:'More Security Safe from No.1',
                priceinfo:'Starting price',
                checktext:'Check Avaliable Shop',
                Warranty:'Warranty',
                icon:<FiCheckSquare/>,
                Authentic:'100% Authentic',
                 // ===============
                infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
                infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
                info1:'Saree',
                info2:'Cotton Jamdani',
                info3:'12.5 Hand',
                info4:'Bangladesh',
                info5:'Gender',
                // ===============
                outsidetext:'Available Shops',
                carttitle:'Cash on Delivery Service',
                stock:'Stock available',
                ratingicon: <FaStar/>,
                amount:1,
                
            },
            {
                id:120,
                image:'https://s.alicdn.com/@sc04/kf/UTB8osj5GtoSdeJk43Owq6ya4XXa9.jpg_300x300.jpg',
                title:'Electric Charge Home Appliance Private Custom Engraving Logo Led Indicator Nose Hair Trimmer',
                bag:<FiShoppingBag/>,
                bagtext:'Buy Now',
                price:450,
                rating:5,
                // ===============
                code:'SKU:0X50874',
                brand:'BRAND',
                number:'No.1',
                more:'More Security Safe from No.1',
                priceinfo:'Starting price',
                checktext:'Check Avaliable Shop',
                Warranty:'Warranty',
                icon:<FiCheckSquare/>,
                Authentic:'100% Authentic',
                 // ===============
                infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
                infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
                info1:'Saree',
                info2:'Cotton Jamdani',
                info3:'12.5 Hand',
                info4:'Bangladesh',
                info5:'Gender',
                // ===============
                outsidetext:'Available Shops',
                carttitle:'Cash on Delivery Service',
                stock:'Stock available',
                ratingicon: <FaStar/>,
                amount:1,
            },
            {
                id:121,
                image:'https://s.alicdn.com/@sc04/kf/H65c25e7ae90344368878dc064a03c8e1S.jpg_300x300.jpg',
                title:'MO-4501 Ambel Hot Sales Microwave Oven Home use cooking appliances Electric Microwave Oven',
                bag:<FiShoppingBag/>,
                bagtext:'Buy Now',
                price:3200,
                rating:5,
                // ===============
                code:'SKU:0X50874',
                brand:'BRAND',
                number:'No.1',
                more:'More Security Safe from No.1',
                priceinfo:'Starting price',
                checktext:'Check Avaliable Shop',
                Warranty:'Warranty',
                icon:<FiCheckSquare/>,
                Authentic:'100% Authentic',
                 // ===============
                infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
                infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
                info1:'Saree',
                info2:'Cotton Jamdani',
                info3:'12.5 Hand',
                info4:'Bangladesh',
                info5:'Gender',
                // ===============
                outsidetext:'Available Shops',
                carttitle:'Cash on Delivery Service',
                stock:'Stock available',
                ratingicon: <FaStar/>,
                amount:1,
            },
            {
                id:122,
                image:'https://s.alicdn.com/@sc04/kf/Hedb44db4125e49ef9260b750345a00a0F.jpg_300x300.jpg',
                title:'2021 Hot sale CCC Certification 360 degree rotated cordless home appliances portable water electric kettle',
                bag:<FiShoppingBag/>,
                bagtext:'Buy Now',
                price:1150,
                rating:5,
                // ===============
                code:'SKU:0X50874',
                brand:'BRAND',
                number:'No.1',
                more:'More Security Safe from No.1',
                priceinfo:'Starting price',
                checktext:'Check Avaliable Shop',
                Warranty:'Warranty',
                icon:<FiCheckSquare/>,
                Authentic:'100% Authentic',
                 // ===============
                infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
                infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
                info1:'Saree',
                info2:'Cotton Jamdani',
                info3:'12.5 Hand',
                info4:'Bangladesh',
                info5:'Gender',
                // ===============
                outsidetext:'Available Shops',
                carttitle:'Cash on Delivery Service',
                stock:'Stock available',
                ratingicon: <FaStar/>,
                amount:1,
            },
            {
                id:123,
                image:'https://s.alicdn.com/@sc04/kf/HTB1yfc1bBWD3KVjSZFsq6AqkpXal.jpg_300x300.jpg',
                title:'1500w Home Kitchen Appliances Stainless Steel Electric Tea Kettle Electric with 2.0L 220V',
                bag:<FiShoppingBag/>,
                bagtext:'Buy Now',
                price:450,
                rating:5,
                // ===============
                code:'SKU:0X50874',
                brand:'BRAND',
                number:'No.1',
                more:'More Security Safe from No.1',
                priceinfo:'Starting price',
                checktext:'Check Avaliable Shop',
                Warranty:'Warranty',
                icon:<FiCheckSquare/>,
                Authentic:'100% Authentic',
                 // ===============
                infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
                infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
                info1:'Saree',
                info2:'Cotton Jamdani',
                info3:'12.5 Hand',
                info4:'Bangladesh',
                info5:'Gender',
                // ===============
                outsidetext:'Available Shops',
                carttitle:'Cash on Delivery Service',
                stock:'Stock available',
                ratingicon: <FaStar/>,
                amount:1,
            },
            {
                id:124,
                image:'https://s.alicdn.com/@sc04/kf/Hab92b3195f9c4c6ca56699d8fc9433ecc.jpg_300x300.jpg',
                title:'USB wholesale home appliance 300ml portable blender PC bottle high speed mixer',
                bag:<FiShoppingBag/>,
                bagtext:'Buy Now',
                price:750,
                rating:5,
                // ===============
                code:'SKU:0X50874',
                brand:'BRAND',
                number:'No.1',
                more:'More Security Safe from No.1',
                priceinfo:'Starting price',
                checktext:'Check Avaliable Shop',
                Warranty:'Warranty',
                icon:<FiCheckSquare/>,
                Authentic:'100% Authentic',
                 // ===============
                infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
                infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
                info1:'Saree',
                info2:'Cotton Jamdani',
                info3:'12.5 Hand',
                iinfo4:'Bangladesh',
                info5:'Gender',
                // ===============
                outsidetext:'Available Shops',
                carttitle:'Cash on Delivery Service',
                stock:'Stock available',
                ratingicon: <FaStar/>,
                amount:1,
            },
        ]
    }
]


export const newsfeeds = [
    {
        title:'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab, temporibus.',
        image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9-foehy4LB0rywbjC8XLwnA29wFW9Q3oE4Q&usqp=CAU',
        news:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, minima magnam maiores illum similique nemo deleniti dolorem vitae a nam quae natus velit debitis iure amet! Et obcaecati, accusamus eveniet itaque nisi possimus. Molestias aut nobis est aliquid amet natus voluptate sed possimus esse incidunt! Cum reprehenderit possimus earum. Nulla repellat pariatur ipsa blanditiis commodi temporibus ipsam laboriosam, deserunt facilis, nemo earum voluptatum omnis numquam placeat esse. Odit, laborum! Esse obcaecati, ab numquam saepe nemo sapiente, rem vel dolorum voluptates corporis id ipsum minima deleniti earum quia debitis, accusantium quibusdam tenetur aliquam iste! Id ipsa hic ut libero blanditiis architecto asperiores quisquam quia quae vero! Provident aliquid ipsam eligendi aliquam. Omnis facilis praesentium optio maiores sequi modi delectus possimus voluptates odit esse laboriosam provident ipsam in, tenetur, magni ea a aut recusandae itaque. Tempora natus laborum, optio temporibus maxime rem voluptatum ab laudantium sit nostrum nemo culpa voluptate aut doloremque quidem eos voluptates consequuntur aliquam. Commodi, veniam ex. Suscipit consequatur vitae distinctio dolores voluptates rem dolore optio excepturi officiis explicabo veritatis, cum eius nihil assumenda soluta in molestias id neque odio quos. Deleniti provident illo laboriosam odio possimus quidem? Dolores qui voluptas quo in, quas soluta. Minima illum consequatur pariatur sunt magni earum sapiente laboriosam qui sed non eveniet deserunt aperiam in eaque sequi dolorem molestias debitis quidem veniam, natus quam. Quis nesciunt laudantium illo saepe optio! Placeat, fugiat? Saepe explicabo, alias dolorum quaerat voluptatem exercitationem, qui voluptatum sint provident quisquam debitis, quam in! Architecto alias delectus doloremque sequi repudiandae?'
    },
    {
        title:'তালেবানের প্রথম সংবাদ সম্মেলন থেকে কী জানা গেল: সার সংক্ষেপ',
        image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMq5R2SnafKht5Cq1uN1R6LwAYUZ2qhb5INw&usqp=CAU',
        news:'তালেবান আফগানিস্তানের দখল নেবার পর তাদের প্রথম সংবাদ সম্মেলনে বিভিন্ন বিষয় নিয়ে কথা বলেছে। তালেবানের মুখপাত্র জাবিউল্লাহ মুজাহিদ সাংবাদিকদের বিভিন্ন প্রশ্নেরও উত্তর দিয়েছেন । তালেবান সরকার গঠনের লক্ষ্যে সক্রিয়ভাবে কাজ করছে। “সব পক্ষ, সব গোষ্ঠী, সবার অন্তর্ভুক্তি আমরা নিশ্চিত করব, কাজ সম্পূর্ণ হলে আমরা সরকার ঘোষণা করব,” বলেছেন মি. মুজাহিদ । তিনি বলেছেন, “নারীরা আমাদের সমাজে খুবই সক্রিয় ভূমিকা রাখবে” এবং তারা বাইরে কাজ করতে পারবে, সেটা হবে “আমাদের শরিয়া আইনের কাঠামোর মধ্যে,”। তিনি সেই কাজের ধরন সম্পর্কে বিস্তারিত কিছু ব্যাখ্যা করেননি । যেসব চুক্তি-ভিত্তিক কর্মী বা দোভাষী বিদেশিদের হয়ে কাজ করেছিল, তাদের ভবিষ্যত সম্পর্কে প্রশ্ন করা হলে মি. মুজাহিদ বলেছেন “কারোর বিরুদ্ধে কোনরকম প্রতিশোধ নেয়া হবে না” এবং তালেবান “আফগানিস্তানের স্থিতিশীলতা ও শান্তির কথা মাথায় রেখে সবাইকে ক্ষমা করেছে।তিনি বলেন তালেবান সংবাদমাধ্যমের ভূমিকাকে সম্মান প্রদর্শনের প্রতিশ্রুতি দিচ্ছে এবং অঙ্গীকার করেছে “বেসরকারি মিডিয়া স্বাধীন ও নিরপেক্ষভাবে কাজ করতে পারবে । কিন্তু মি. মুজাহিদ সতর্ক করে দিয়েছেন যে “মিডিয়া আমাদের বিরুদ্ধে কাজ করতে পারবে না। তালেবান শাসনের অধীনে আফগানিস্তান আল-কায়দা বা অন্য চরমপন্থী যোদ্ধাদের নিরাপদ আশ্রয়স্থল হয়ে উঠবে কিনা- এই ঝুঁকি সম্পর্কে সাংবাদিকদের প্রশ্নের উত্তরে মি. মুজাহিদ বলেছেন যে “আফগানিস্তানের মাটি কারোর বিরুদ্ধে ব্যবহার করতে দেয়া হবে না। তিনি আরও দাবি করেন যে তালেবান তাদের অগ্রযাত্রা “কাবুলের প্রবেশ দ্বারগুলোতে এসে থামানোর পরিকল্পনা করেছিল, যাতে ক্ষমতার হস্তান্তর প্রক্রিয়া নির্বিঘ্নে সম্পন্ন হতে পারে,” কিন্তু তিনি বলেন পরিস্থিতি অন্য দিকে মোড় নেয়ায় “শহরের বাসিন্দাদের নিরাপত্তা নিশ্চিত করতে” তারা কাবুলে ঢুকতে বাধ্য হন।',
    },
    {
        title:'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab, temporibus.',
        image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT25EPb98h91BnLVH5fVpTs3r4MtxPdAfSFhQ&usqp=CAU',
        news:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, minima magnam maiores illum similique nemo deleniti dolorem vitae a nam quae natus velit debitis iure amet! Et obcaecati, accusamus eveniet itaque nisi possimus. Molestias aut nobis est aliquid amet natus voluptate sed possimus esse incidunt! Cum reprehenderit possimus earum. Nulla repellat pariatur ipsa blanditiis commodi temporibus ipsam laboriosam, deserunt facilis, nemo earum voluptatum omnis numquam placeat esse. Odit, laborum! Esse obcaecati, ab numquam saepe nemo sapiente, rem vel dolorum voluptates corporis id ipsum minima deleniti earum quia debitis, accusantium quibusdam tenetur aliquam iste! Id ipsa hic ut libero blanditiis architecto asperiores quisquam quia quae vero! Provident aliquid ipsam eligendi aliquam. Omnis facilis praesentium optio maiores sequi modi delectus possimus voluptates odit esse laboriosam provident ipsam in, tenetur, magni ea a aut recusandae itaque. Tempora natus laborum, optio temporibus maxime rem voluptatum ab laudantium sit nostrum nemo culpa voluptate aut doloremque quidem eos voluptates consequuntur aliquam. Commodi, veniam ex. Suscipit consequatur vitae distinctio dolores voluptates rem dolore optio excepturi officiis explicabo veritatis, cum eius nihil assumenda soluta in molestias id neque odio quos. Deleniti provident illo laboriosam odio possimus quidem? Dolores qui voluptas quo in, quas soluta. Minima illum consequatur pariatur sunt magni earum sapiente laboriosam qui sed non eveniet deserunt aperiam in eaque sequi dolorem molestias debitis quidem veniam, natus quam. Quis nesciunt laudantium illo saepe optio! Placeat, fugiat? Saepe explicabo, alias dolorum quaerat voluptatem exercitationem, qui voluptatum sint provident quisquam debitis, quam in! Architecto alias delectus doloremque sequi repudiandae?'
    },
    {
        title:'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab, temporibus.',
        image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNUjDWDqF0fq-k6SnXp--vHtjUhPFOQsPFOw&usqp=CAU',
        news:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odio, minima magnam maiores illum similique nemo deleniti dolorem vitae a nam quae natus velit debitis iure amet! Et obcaecati, accusamus eveniet itaque nisi possimus. Molestias aut nobis est aliquid amet natus voluptate sed possimus esse incidunt! Cum reprehenderit possimus earum. Nulla repellat pariatur ipsa blanditiis commodi temporibus ipsam laboriosam, deserunt facilis, nemo earum voluptatum omnis numquam placeat esse. Odit, laborum! Esse obcaecati, ab numquam saepe nemo sapiente, rem vel dolorum voluptates corporis id ipsum minima deleniti earum quia debitis, accusantium quibusdam tenetur aliquam iste! Id ipsa hic ut libero blanditiis architecto asperiores quisquam quia quae vero! Provident aliquid ipsam eligendi aliquam. Omnis facilis praesentium optio maiores sequi modi delectus possimus voluptates odit esse laboriosam provident ipsam in, tenetur, magni ea a aut recusandae itaque. Tempora natus laborum, optio temporibus maxime rem voluptatum ab laudantium sit nostrum nemo culpa voluptate aut doloremque quidem eos voluptates consequuntur aliquam. Commodi, veniam ex. Suscipit consequatur vitae distinctio dolores voluptates rem dolore optio excepturi officiis explicabo veritatis, cum eius nihil assumenda soluta in molestias id neque odio quos. Deleniti provident illo laboriosam odio possimus quidem? Dolores qui voluptas quo in, quas soluta. Minima illum consequatur pariatur sunt magni earum sapiente laboriosam qui sed non eveniet deserunt aperiam in eaque sequi dolorem molestias debitis quidem veniam, natus quam. Quis nesciunt laudantium illo saepe optio! Placeat, fugiat? Saepe explicabo, alias dolorum quaerat voluptatem exercitationem, qui voluptatum sint provident quisquam debitis, quam in! Architecto alias delectus doloremque sequi repudiandae?'
    },
]



export const detailpage = [
     {
                id: 103,
                image: 'https://s.alicdn.com/@sc04/kf/U231e91c10dad4772993fccfd7ac557cfU.jpg_300x300.jpg',
                title:'Dcb Fashion Exports Indian Embroidery Wedding & Party Wear Silk Maroon Saree with Heavy Work Bridal Sarees Low Price',
                betweenprice:'2500.00 - 1000.00/ Piece',
                bag:<FiShoppingBag/>,
                bagtext:'Buy Now',
                // cart list End here 
                code:'SKU:0X50874',
                brand:'BRAND',
                number:'No.1',
                more:'More Security Safe from No.1',
                price: 4500,
                priceinfo:'Starting price',
                checktext:'Check Avaliable Shop',
                Warranty:'Warranty',
                icon:<FiCheckSquare/>,
                Authentic:'100% Authentic',
                // review End here 

                infoOne:'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit perspiciatis soluta accusantium, porro quam ipsum laboriosam, fugit quod quos nihil odit beatae consequatur eligendi dolorum eius fuga molestiae, corporis natus aliquam vitae dignissimos iure? Consequuntur aspernatur in id excepturi pariatur ipsum ducimus illum, totam repellendus itaque libero ad commodi enim?',
                infoTwo:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem mollitia neque similique veniam ipsum expedita voluptates fuga, magni cumque laboriosam? Enim reprehenderit nesciunt, deleniti qui inventore molestias, eos officia ex tenetur iusto quos corrupti blanditiis, consectetur similique ipsa aliquid saepe',
                info1:'Saree',
                info2:'Cotton Jamdani',
                info3:'12.5 Hand',
                info4:'Blouse Piece',
                info5:'Gender',
                // details End here
                outsidetext:'Available Shops',
                carttitle:'Cash on Delivery Service',
                stock:'Stock available',
                rating:5,
                ratingicon: <FaStar/>,
                amount:1,
            },
]